### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by Jopoleon** [RobertoPrevato/jQuery-KingTable#9]
Hello! I caught error when used KingTable with data of following format: 
All data :  [Object, Object, Object, Object…]
Object: Object
CampaignID:13572830
ClicksContext:0
ClicksSearch:0
GoalConversionContext:0
GoalConversionSearch:0
GoalCostContext:0
GoalCostSearch:0
SessionDepthContext:0
SessionDepthSearch:0
ShowsContext:0
ShowsSearch:1
StatDate:"2015-10-11"
SumContext:0
SumSearch:0
__proto__:Object

**The error:**
```
Uncaught (in promise) TypeError: Cannot read property 'length' of null
    at s (http://localhost:3000/static/js/libs/kingtable.js:66:33)
    at Object.compareStrings (http://localhost:3000/static/js/libs/kingtable.js:131:14)
    at http://localhost:3000/static/js/libs/kingtable.js:173:33
    at Array.sort (native)
    at Object.sortBy (http://localhost:3000/static/js/libs/kingtable.js:154:14)
    at t.value (http://localhost:3000/static/js/libs/kingtable.js:4049:41)
    at t.value (http://localhost:3000/static/js/libs/kingtable.js:4023:13)
    at t.value (http://localhost:3000/static/js/libs/kingtable.js:4716:17)
    at t.value (http://localhost:3000/static/js/libs/kingtable.js:4653:31)
    at t.value (http://localhost:3000/static/js/libs/kingtable.js:4635:49)
s @ kingtable.js:66
compareStrings @ kingtable.js:131
(anonymous) @ kingtable.js:173
sortBy @ kingtable.js:154
value @ kingtable.js:4049
value @ kingtable.js:4023
value @ kingtable.js:4716
value @ kingtable.js:4653
value @ kingtable.js:4635
value @ kingtable.js:3842
i @ kingtable.js:3775
a @ kingtable.js:3779
(anonymous) @ kingtable.js:3797
value @ kingtable.js:3773
value @ kingtable.js:5086
u @ kingtable.js:2034
```
Can somebody help me with that?

**Comment by RobertoPrevato** [comment]
Closing this issue because it refers to [KingTable library](https://github.com/RobertoPrevato/KingTable) and an issue was created for it, too - [here](https://github.com/RobertoPrevato/KingTable/issues/1). jQuery-KingTable library is the previous version and is very much different.
